# Generated by Django 3.2.8 on 2021-10-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Время и дата записи')),
                ('user', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('washingMachiene1', models.BooleanField(verbose_name='Занятость')),
            ],
        ),
    ]
