# Generated by Django 3.2.8 on 2021-10-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signups',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='signups',
            name='washingMachiene1',
        ),
        migrations.AddField(
            model_name='signups',
            name='wm1',
            field=models.BooleanField(default=0, verbose_name='wm1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signups',
            name='wm2',
            field=models.BooleanField(default=0, verbose_name='wm2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signups',
            name='wm3',
            field=models.BooleanField(default=0, verbose_name='wm3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signups',
            name='wm4',
            field=models.BooleanField(default=0, verbose_name='wm4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signups',
            name='wm5',
            field=models.BooleanField(default=0, verbose_name='wm5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signups',
            name='wm6',
            field=models.BooleanField(default=0, verbose_name='wm6'),
            preserve_default=False,
        ),
    ]
